local ROOT = fs.getDir(shell.getRunningProgram())
if ROOT == "" then ROOT = "." end
package.path = package.path .. ";" .. fs.combine(ROOT, "?.lua")
    .. ";" .. fs.combine(ROOT, "?/init.lua")

local config = require("config")
local util = require("lib.util")
local net = require("lib.net")
local ui = require("lib.ui")
local onlineUpdate = require("lib.update")

local DEPLOY_PROTOCOL = "PUMPE_DEPLOY_V5"
local DEPLOY_HOSTNAME = "PUMPE_UPDATES"
local DEPLOY_CODE = "4040"
local DEPLOY_CHUNK_SIZE = 6000
local UPDATES_DIR = "/updates"

local LOCAL_UPDATE_FILES = {
    "bank_server.lua",
    "pumpe.lua",
    "service_kiosk.lua",
    "event_kiosk.lua",
    "tax_controller.lua",
    "startup.lua",
    "launcher.lua",
    "config.lua",
    "lib/net.lua",
    "lib/ui.lua",
    "lib/update.lua",
    "lib/util.lua",
}

local ROLE_MAIN_FILES = {
    bank = "bank_server.lua",
    pumpe = "pumpe.lua",
    service = "service_kiosk.lua",
    event = "event_kiosk.lua",
    tax = "tax_controller.lua",
}

local COMMON_UPDATE_FILES = {
    { path = "launcher.lua", source = "launcher.lua" },
    { path = "installer.lua", source = "startup.lua" },
    { path = "lib/net.lua", source = "lib/net.lua" },
    { path = "lib/ui.lua", source = "lib/ui.lua" },
    { path = "lib/util.lua", source = "lib/util.lua" },
}

local BANK_UPDATE_FILES = {
    { path = "lib/update.lua", source = "lib/update.lua" },
}

local function protectedDeployRole(role)
    return role == "bank" or role == "tax"
end

local function deploymentFilesForRole(role)
    local mainFile = ROLE_MAIN_FILES[role]
    if not mainFile then return nil end
    local files = {
        {
            path = "config.lua",
            source = protectedDeployRole(role)
                and "config.lua" or "public/config.lua",
        },
    }
    for _, file in ipairs(COMMON_UPDATE_FILES) do
        files[#files + 1] = { path = file.path, source = file.source }
    end
    if role == "bank" then
        for _, file in ipairs(BANK_UPDATE_FILES) do
            files[#files + 1] = { path = file.path, source = file.source }
        end
    end
    files[#files + 1] = { path = mainFile, source = mainFile }
    return files
end

local function writePublicDeployConfig()
    local publicConfig = util.copy(config)
    publicConfig.government_key = "CLIENT-NO-GOVERNMENT-ACCESS"
    local path = fs.combine(UPDATES_DIR, "public/config.lua")
    local directory = fs.getDir(path)
    if not fs.exists(directory) then fs.makeDir(directory) end
    util.writeFile(path, "-- Generated by the PUMPE Bank Server.\nreturn "
        .. textutils.serialize(publicConfig, { compact = false }) .. "\n")
end

local function updateDepotMissingFiles()
    local missing = {}
    for _, path in ipairs(LOCAL_UPDATE_FILES) do
        local source = fs.combine(ROOT, path)
        local destination = fs.combine(UPDATES_DIR, path)
        local sourceBody = util.readFile(source)
        if not sourceBody then
            missing[#missing + 1] = path .. " (local source)"
        elseif util.readFile(destination) ~= sourceBody then
            missing[#missing + 1] = path
        end
    end
    local publicConfig = fs.combine(UPDATES_DIR, "public/config.lua")
    if not fs.exists(publicConfig) or fs.isDir(publicConfig) then
        missing[#missing + 1] = "public/config.lua"
    end
    return missing
end

local function stageLocalUpdateFiles()
    local staged = 0
    for _, path in ipairs(LOCAL_UPDATE_FILES) do
        local source = fs.combine(ROOT, path)
        local destination = fs.combine(UPDATES_DIR, path)
        local body = util.readFile(source)
        if body then
            local ok = pcall(util.writeFile, destination, body)
            if ok and util.readFile(destination) == body then
                staged = staged + 1
            end
        end
    end
    return staged
end

local function renderUpdateBootstrap(created, staged, missing)
    local target = term.current()
    local width, height = target.getSize()
    ui.clear(target)
    ui.header(target, "EASY DEPLOYMENT SETUP", "/updates/")
    ui.text(target, 2, 5, created and "UPDATE DEPOT CREATED" or "UPDATE DEPOT CHECK",
        created and ui.theme.success or ui.theme.accent)
    ui.text(target, 2, 7, "Synced locally: " .. staged .. "/" .. #LOCAL_UPDATE_FILES,
        ui.theme.ink)
    if #missing == 0 then
        ui.text(target, 2, 9, "All deployment files are ready.", ui.theme.success)
        ui.text(target, 2, 11, "Restart once to enable installer downloads.",
            ui.theme.muted)
    else
        ui.text(target, 2, 9, "Missing " .. #missing .. " required file(s):",
            ui.theme.danger)
        local visible = math.max(1, height - 14)
        for index = 1, math.min(#missing, visible) do
            ui.text(target, 4, 10 + index, ui.truncate(missing[index], width - 6),
                ui.theme.warning)
        end
        ui.text(target, 2, height - 3,
            "Add them beside bank_server.lua, then rescan.", ui.theme.muted)
    end
    local scene = ui.scene(target)
    if #missing == 0 then
        scene:button("restart", 2, height - 1, 15, 1, "RESTART NOW",
            { background = ui.theme.success, foreground = colors.black })
    else
        scene:button("rescan", 2, height - 1, 12, 1, "RESCAN",
            { background = ui.theme.accentDark })
    end
    scene:button("shutdown", width - 11, height - 1, 10, 1, "SHUTDOWN",
        { background = ui.theme.danger })
    return scene
end

local function bootstrapUpdateDepot()
    if fs.exists(UPDATES_DIR) and not fs.isDir(UPDATES_DIR) then
        ui.clear(term.current())
        ui.header(term.current(), "DEPLOYMENT BLOCKED", "/updates is not a folder")
        ui.text(term.current(), 2, 6, "Rename or remove the /updates file.", ui.theme.danger)
        ui.text(term.current(), 2, 8, "The Bank Server needs /updates/ as a directory.",
            ui.theme.muted)
        sleep(3)
        error("/updates must be a directory")
    end

    local created = not fs.exists(UPDATES_DIR)
    if created then
        fs.makeDir(UPDATES_DIR)
    end

    local staged = stageLocalUpdateFiles()
    writePublicDeployConfig()
    local missing = updateDepotMissingFiles()
    if not created and #missing == 0 then return end

    while true do
        local scene = renderUpdateBootstrap(created, staged, missing)
        local bootstrapKeys = {}
        if type(keys) == "table" and type(keys.enter) == "number" then
            bootstrapKeys[keys.enter] = #missing == 0 and "restart" or "rescan"
        end
        local action = scene:wait({
            keys = bootstrapKeys,
        })
        if action == "restart" and #missing == 0 then
            os.reboot()
        elseif action == "rescan" then
            staged = stageLocalUpdateFiles()
            writePublicDeployConfig()
            missing = updateDepotMissingFiles()
        elseif action == "shutdown" or action == "__terminate" then
            os.shutdown()
        end
    end
end

bootstrapUpdateDepot()

local DATA_FILE = fs.combine(ROOT, config.data_file)
local sessions = {}
local governmentSessions = {}
local activity = {}
local running = true

local function blankState()
    return {
        schema = 5,
        created_at = util.nowMs(),
        sequence = {
            account = 0, company = 0, terminal = 0, event = 0,
            ticket_type = 0, ticket = 0, transaction = 0,
            period = 0, notification = 0, subscription = 0,
            request = 0,
        },
        accounts = {},
        account_names = {},
        companies = {},
        terminals = {},
        events = {},
        ticket_types = {},
        tickets = {},
        transactions = {},
        declaration_periods = {},
        declarations = {},
        active_pay_codes = {},
        payment_requests = {},
        gps_devices = {},
        tax_revenue = 0,
        last_subscription_day = -1,
    }
end

local state = util.loadTable(DATA_FILE, blankState())

local function ensureState()
    local defaults = blankState()
    for key, value in pairs(defaults) do
        if state[key] == nil then state[key] = util.copy(value) end
    end
    for key, value in pairs(defaults.sequence) do
        if state.sequence[key] == nil then state.sequence[key] = value end
    end
    state.account_names = state.account_names or {}
    for _, account in pairs(state.accounts) do
        account.notifications = account.notifications or {}
        account.subscriptions = account.subscriptions or {}
        account.daily_spent = account.daily_spent or 0
        account.last_spent_day = account.last_spent_day or util.ingameDay()
        if account.name then
            state.account_names[util.normalName(account.name)] = account.account_id
        end
    end
    for _, terminal in pairs(state.terminals) do
        terminal.balance = terminal.balance or 0
        terminal.sales_total = terminal.sales_total or 0
        terminal.quick_items = terminal.quick_items or {}
        terminal.status = terminal.status or "active"
    end
    for _, company in pairs(state.companies) do
        company.quick_items = company.quick_items or {}
        company.linked_terminal_ids = company.linked_terminal_ids or {}
        company.status = company.status or "active"
    end
    for _, event in pairs(state.events) do
        event.ticket_type_ids = event.ticket_type_ids or {}
        event.status = event.status or "active"
    end
end

ensureState()

local function save()
    util.saveTable(DATA_FILE, state)
end

local function logActivity(text, color)
    table.insert(activity, 1, {
        text = util.safeText(text, 42),
        color = color or colors.lightGray,
        time = util.formatClock(),
    })
    while #activity > 8 do table.remove(activity) end
end

local function reject(code, message)
    error({ pumpe = true, code = code, message = message }, 0)
end

local function need(condition, code, message)
    if not condition then reject(code, message) end
end

local prefixes = {
    account = { "ACC", 6 },
    company = { "CMP", 6 },
    terminal = { "TERM", 5 },
    event = { "EVT", 6 },
    ticket_type = { "TT", 6 },
    ticket = { "TICK", 10 },
    transaction = { "TX", 10 },
    period = { "PER", 6 },
    notification = { "NOT", 8 },
    subscription = { "SUB", 8 },
    request = { "REQ", 8 },
}

local function nextId(kind)
    state.sequence[kind] = (state.sequence[kind] or 0) + 1
    local format = prefixes[kind]
    return format[1] .. string.format("%0" .. format[2] .. "d", state.sequence[kind])
end

local function accountByName(name)
    local id = state.account_names[util.normalName(name)]
    return id and state.accounts[id] or nil
end

local function publicAccount(account)
    return {
        account_id = account.account_id,
        name = account.name,
        gender = account.gender,
        balance = account.balance,
        personal_number = account.personal_number,
        card_id = account.card_id,
        frozen = account.frozen,
        smart_declaration_lifetime = account.smart_declaration_lifetime,
        daily_spent = account.daily_spent,
    }
end

local function resetDailySpend(account)
    local day = util.ingameDay()
    if account.last_spent_day ~= day then
        account.last_spent_day = day
        account.daily_spent = 0
    end
end

local function verifyAccount(account, pin)
    return account and account.pin_hash == util.hashPin(pin)
end

local function checkAccountActive(account)
    need(account, "ACCOUNT_NOT_FOUND", "Account not found")
    need(not account.banned, "ACCOUNT_BANNED", "This account is banned")
    need(not account.frozen, "ACCOUNT_FROZEN", "This account is frozen")
end

local function createSession(account)
    local token = util.token("SESSION")
    sessions[token] = {
        account_id = account.account_id,
        expires_at = util.nowMs() + config.session_ttl_ms,
    }
    return token
end

local function requireSession(payload)
    local session = sessions[payload and payload.session_token]
    need(session and session.expires_at > util.nowMs(),
        "SESSION_EXPIRED", "Please sign in again")
    local account = state.accounts[session.account_id]
    checkAccountActive(account)
    resetDailySpend(account)
    return account
end

local function requireTerminal(payload)
    local terminal = state.terminals[payload and payload.terminal_id]
    need(terminal and terminal.auth_token == payload.terminal_token,
        "TERMINAL_AUTH", "Kiosk is not registered")
    need(terminal.status == "active", "TERMINAL_INACTIVE", "Kiosk is inactive")
    terminal.last_seen = util.nowMs()
    return terminal
end

local function requireGovernment(payload)
    local session = governmentSessions[payload and payload.government_token]
    need(session and session.expires_at > util.nowMs(),
        "GOVERNMENT_AUTH", "Government session expired")
    session.expires_at = util.nowMs() + config.session_ttl_ms
    return session
end

local function notification(account, title, body, kind)
    local item = {
        notification_id = nextId("notification"),
        title = util.safeText(title, 40),
        body = util.safeText(body, 120),
        kind = kind or "info",
        created_day = util.ingameDay(),
        created_time = util.formatClock(),
        read = false,
    }
    table.insert(account.notifications, 1, item)
    while #account.notifications > 50 do table.remove(account.notifications) end
    return item
end

local function transaction(account, kind, amount, counterparty, description, extra)
    local item = {
        tx_id = nextId("transaction"),
        account_id = account and account.account_id or nil,
        type = kind,
        amount = util.roundMoney(amount) or 0,
        counterparty = util.safeText(counterparty, 40),
        description = util.safeText(description, 100),
        company_id = extra and extra.company_id or nil,
        terminal_id = extra and extra.terminal_id or nil,
        tax_amount = extra and extra.tax_amount or 0,
        day = util.ingameDay(),
        time = util.formatClock(),
        timestamp = util.nowMs(),
    }
    table.insert(state.transactions, item)
    while #state.transactions > 3000 do table.remove(state.transactions, 1) end
    return item
end

local function companyOwner(terminal)
    local company = terminal.company_id and state.companies[terminal.company_id] or nil
    local owner = company and state.accounts[company.owner_account_id] or nil
    return company, owner
end

local function merchantBalance(terminal)
    local _, owner = companyOwner(terminal)
    return owner and owner.balance or terminal.balance
end

local function creditMerchant(terminal, amount, description, payer)
    local company, owner = companyOwner(terminal)
    if owner then
        owner.balance = util.roundMoney(owner.balance + amount)
        transaction(owner, "merchant_credit", amount,
            payer and payer.name or terminal.name, description, {
                company_id = company.company_id,
                terminal_id = terminal.terminal_id,
            })
        notification(owner, "Sale received", util.money(amount, config.currency)
            .. " via " .. terminal.name, "money")
    else
        terminal.balance = util.roundMoney(terminal.balance + amount)
    end
    terminal.sales_total = util.roundMoney((terminal.sales_total or 0) + amount)
end

local function debitMerchant(terminal, amount, description, recipient)
    local company, owner = companyOwner(terminal)
    if owner then
        need(owner.balance >= amount, "INSUFFICIENT_FUNDS",
            "Merchant balance is too low")
        owner.balance = util.roundMoney(owner.balance - amount)
        transaction(owner, "merchant_debit", -amount,
            recipient and recipient.name or terminal.name, description, {
                company_id = company.company_id,
                terminal_id = terminal.terminal_id,
            })
    else
        need(terminal.balance >= amount, "INSUFFICIENT_FUNDS",
            "Kiosk balance is too low")
        terminal.balance = util.roundMoney(terminal.balance - amount)
    end
end

local function quickItems(terminal)
    local company = terminal.company_id and state.companies[terminal.company_id]
    return company and company.quick_items or terminal.quick_items
end

local function cleanupEphemeral()
    local now = util.nowMs()
    for code, payment in pairs(state.active_pay_codes) do
        if payment.expires_at <= now and payment.status == "pending" then
            payment.status = "expired"
        elseif payment.expires_at + 10 * 60 * 1000 < now then
            state.active_pay_codes[code] = nil
        end
    end
    for id, request in pairs(state.payment_requests) do
        if request.expires_at <= now and request.status == "pending" then
            request.status = "expired"
        elseif request.expires_at + 10 * 60 * 1000 < now then
            state.payment_requests[id] = nil
        end
    end
    for token, session in pairs(sessions) do
        if session.expires_at <= now then sessions[token] = nil end
    end
    for token, session in pairs(governmentSessions) do
        if session.expires_at <= now then governmentSessions[token] = nil end
    end
end

local function validateAmount(value, maximum)
    local amount = util.roundMoney(value)
    need(amount and amount > 0, "INVALID_AMOUNT", "Enter an amount above zero")
    need(not maximum or amount <= maximum, "INVALID_AMOUNT",
        "Amount is above the allowed maximum")
    return amount
end

local actions = {}

function actions.PING()
    return {
        version = config.version,
        day = util.ingameDay(),
        time = util.formatClock(),
    }
end

function actions.REGISTER(payload)
    local name = util.safeText(util.trim(payload.name), 20)
    need(name:match("^[%w_ %-]+$") and #name >= 2,
        "INVALID_NAME", "Use 2-20 letters, numbers, spaces, _ or -")
    need(not accountByName(name), "NAME_TAKEN", "That account name is taken")
    need(util.validPin(payload.pin), "INVALID_PIN", "PIN must be four digits")

    local accountId = nextId("account")
    local personalNumber
    repeat personalNumber = util.randomString(5, "0123456789")
        local duplicate = false
        for _, existing in pairs(state.accounts) do
            if existing.personal_number == personalNumber then duplicate = true break end
        end
    until not duplicate

    local account = {
        account_id = accountId,
        name = name,
        pin_hash = util.hashPin(payload.pin),
        gender = util.safeText(payload.gender or "Not set", 20),
        balance = config.starting_balance,
        personal_number = personalNumber,
        card_id = "PUMPE_" .. accountId,
        frozen = false,
        banned = false,
        smart_declaration_lifetime = false,
        subscriptions = {},
        notifications = {},
        daily_spent = 0,
        last_spent_day = util.ingameDay(),
        created_day = util.ingameDay(),
    }
    state.accounts[accountId] = account
    state.account_names[util.normalName(name)] = accountId
    notification(account, "Welcome to PUMPE",
        "Your account starts with " .. util.money(config.starting_balance, config.currency),
        "success")
    transaction(account, "opening_credit", config.starting_balance,
        "PUMPE Bank", "Starting balance")
    save()
    logActivity("New account: " .. name, colors.lime)
    return { account = publicAccount(account), session_token = createSession(account) }
end

function actions.LOGIN(payload)
    local account = accountByName(payload.name)
    need(verifyAccount(account, payload.pin), "BAD_LOGIN", "Name or PIN is incorrect")
    checkAccountActive(account)
    resetDailySpend(account)
    logActivity("Login: " .. account.name, colors.cyan)
    return { account = publicAccount(account), session_token = createSession(account) }
end

function actions.ACCOUNT_SUMMARY(payload)
    local account = requireSession(payload)
    local unread = 0
    for _, item in ipairs(account.notifications) do
        if not item.read then unread = unread + 1 end
    end
    local pending = 0
    for _, request in pairs(state.payment_requests) do
        if request.account_id == account.account_id and request.status == "pending"
            and request.expires_at > util.nowMs() then pending = pending + 1 end
    end
    return {
        account = publicAccount(account),
        unread_notifications = unread,
        pending_requests = pending,
        day = util.ingameDay(),
        time = util.formatClock(),
    }
end

function actions.SEND_MONEY(payload)
    local sender = requireSession(payload)
    local recipient = accountByName(payload.recipient)
    checkAccountActive(recipient)
    need(recipient.account_id ~= sender.account_id,
        "INVALID_RECIPIENT", "You cannot send money to yourself")
    need(verifyAccount(sender, payload.pin), "BAD_PIN", "Incorrect PIN")
    local amount = validateAmount(payload.amount)
    need(sender.balance >= amount, "INSUFFICIENT_FUNDS", "Not enough money")
    sender.balance = util.roundMoney(sender.balance - amount)
    recipient.balance = util.roundMoney(recipient.balance + amount)
    sender.daily_spent = util.roundMoney(sender.daily_spent + amount)
    transaction(sender, "transfer_out", -amount, recipient.name,
        payload.description or "Money sent")
    transaction(recipient, "transfer_in", amount, sender.name,
        payload.description or "Money received")
    notification(recipient, "Money received",
        sender.name .. " sent you " .. util.money(amount, config.currency), "money")
    save()
    logActivity("Transfer " .. util.money(amount, config.currency)
        .. " " .. sender.name .. " > " .. recipient.name, colors.lime)
    return { balance = sender.balance, recipient = recipient.name, amount = amount }
end

function actions.HISTORY(payload)
    local account = requireSession(payload)
    local output = {}
    for index = #state.transactions, 1, -1 do
        local item = state.transactions[index]
        if item.account_id == account.account_id then
            output[#output + 1] = util.copy(item)
            if #output >= 50 then break end
        end
    end
    return { transactions = output }
end

function actions.NOTIFICATIONS(payload)
    local account = requireSession(payload)
    return { notifications = util.copy(account.notifications) }
end

function actions.MARK_NOTIFICATIONS_READ(payload)
    local account = requireSession(payload)
    for _, item in ipairs(account.notifications) do item.read = true end
    save()
    return { ok = true }
end

function actions.LIST_SUBSCRIPTIONS(payload)
    local account = requireSession(payload)
    local output = util.sortedValues(account.subscriptions, nil, function(a, b)
        if a.active ~= b.active then return a.active end
        return a.next_charge_day < b.next_charge_day
    end)
    return { subscriptions = util.copy(output) }
end

function actions.CANCEL_SUBSCRIPTION(payload)
    local account = requireSession(payload)
    local subscription = account.subscriptions[payload.subscription_id]
    need(subscription and subscription.active, "NOT_FOUND", "Subscription not found")
    subscription.active = false
    subscription.cancelled_day = util.ingameDay()
    save()
    return { subscription = util.copy(subscription) }
end

function actions.PAY_CODE_PREVIEW(payload)
    local account = requireSession(payload)
    cleanupEphemeral()
    local code = string.upper(util.trim(payload.code))
    local payment = state.active_pay_codes[code]
    need(payment and payment.status == "pending"
        and payment.expires_at > util.nowMs(),
        "BAD_CODE", "Code is invalid or expired")
    local terminal = state.terminals[payment.terminal_id]
    need(terminal, "TERMINAL_NOT_FOUND", "Kiosk no longer exists")
    resetDailySpend(account)
    local pinRequired = payment.kind ~= "withdrawal"
        and (payment.amount > config.pin_free_limit
            or account.daily_spent + payment.amount > config.daily_spend_limit)
    return {
        code = code,
        kind = payment.kind,
        amount = payment.amount,
        merchant = terminal.name,
        items = util.copy(payment.items or {}),
        description = payment.description,
        pin_required = pinRequired,
        expires_in_ms = payment.expires_at - util.nowMs(),
    }
end

local function settleCode(account, payment, pin)
    local terminal = state.terminals[payment.terminal_id]
    need(terminal, "TERMINAL_NOT_FOUND", "Kiosk no longer exists")
    resetDailySpend(account)
    if payment.kind == "withdrawal" then
        debitMerchant(terminal, payment.amount,
            "Withdrawal code " .. payment.code, account)
        account.balance = util.roundMoney(account.balance + payment.amount)
        transaction(account, "kiosk_withdrawal", payment.amount,
            terminal.name, payment.description or "Kiosk withdrawal", {
                company_id = terminal.company_id,
                terminal_id = terminal.terminal_id,
            })
        notification(account, "Withdrawal received",
            util.money(payment.amount, config.currency) .. " from " .. terminal.name,
            "money")
    else
        local pinRequired = payment.amount > config.pin_free_limit
            or account.daily_spent + payment.amount > config.daily_spend_limit
        if pinRequired then
            need(verifyAccount(account, pin), "BAD_PIN", "Incorrect PIN")
        end
        need(account.balance >= payment.amount, "INSUFFICIENT_FUNDS", "Not enough money")
        account.balance = util.roundMoney(account.balance - payment.amount)
        account.daily_spent = util.roundMoney(account.daily_spent + payment.amount)
        creditMerchant(terminal, payment.amount,
            payment.description or "Kiosk payment", account)
        transaction(account, "purchase", -payment.amount, terminal.name,
            payment.description or "Kiosk payment", {
                company_id = terminal.company_id,
                terminal_id = terminal.terminal_id,
            })
        notification(account, "Payment accepted",
            util.money(payment.amount, config.currency) .. " at " .. terminal.name,
            "success")
    end
    payment.status = "paid"
    payment.paid_by = account.account_id
    payment.paid_at = util.nowMs()
    save()
    logActivity("Code " .. payment.code .. " paid "
        .. util.money(payment.amount, config.currency), colors.lime)
    return {
        amount = payment.amount,
        kind = payment.kind,
        merchant = terminal.name,
        balance = account.balance,
    }
end

function actions.PAY_CODE_CONFIRM(payload)
    local account = requireSession(payload)
    cleanupEphemeral()
    local code = string.upper(util.trim(payload.code))
    local payment = state.active_pay_codes[code]
    need(payment and payment.status == "pending"
        and payment.expires_at > util.nowMs(),
        "BAD_CODE", "Code is invalid or expired")
    return settleCode(account, payment, payload.pin)
end

function actions.GPS_UPDATE(payload)
    local account = requireSession(payload)
    need(type(payload.x) == "number" and type(payload.y) == "number"
        and type(payload.z) == "number", "GPS_FAILED", "No GPS position")
    state.gps_devices[account.account_id] = {
        account_id = account.account_id,
        x = payload.x, y = payload.y, z = payload.z,
        updated_at = util.nowMs(),
    }
    return { ok = true }
end

function actions.PENDING_REQUESTS(payload)
    local account = requireSession(payload)
    cleanupEphemeral()
    local output = {}
    for _, request in pairs(state.payment_requests) do
        if request.account_id == account.account_id and request.status == "pending"
            and request.expires_at > util.nowMs() then
            local terminal = state.terminals[request.terminal_id]
            output[#output + 1] = {
                request_id = request.request_id,
                amount = request.amount,
                description = request.description,
                merchant = terminal and terminal.name or "Kiosk",
                expires_in_ms = request.expires_at - util.nowMs(),
            }
        end
    end
    table.sort(output, function(a, b) return a.expires_in_ms < b.expires_in_ms end)
    return { requests = output }
end

function actions.RESPOND_PAYMENT_REQUEST(payload)
    local account = requireSession(payload)
    local request = state.payment_requests[payload.request_id]
    need(request and request.account_id == account.account_id
        and request.status == "pending" and request.expires_at > util.nowMs(),
        "REQUEST_EXPIRED", "Payment request expired")
    if not payload.approve then
        request.status = "declined"
        save()
        return { status = "declined" }
    end
    local terminal = state.terminals[request.terminal_id]
    need(terminal, "TERMINAL_NOT_FOUND", "Kiosk no longer exists")
    need(verifyAccount(account, payload.pin), "BAD_PIN", "Incorrect PIN")
    need(account.balance >= request.amount, "INSUFFICIENT_FUNDS", "Not enough money")
    account.balance = util.roundMoney(account.balance - request.amount)
    account.daily_spent = util.roundMoney(account.daily_spent + request.amount)
    creditMerchant(terminal, request.amount, request.description, account)
    transaction(account, "proximity_purchase", -request.amount, terminal.name,
        request.description, {
            company_id = terminal.company_id,
            terminal_id = terminal.terminal_id,
        })
    request.status = "paid"
    request.paid_at = util.nowMs()
    notification(account, "Payment accepted",
        util.money(request.amount, config.currency) .. " at " .. terminal.name,
        "success")
    save()
    return { status = "paid", balance = account.balance }
end

function actions.LIST_EVENTS(payload)
    requireSession(payload)
    local today = util.ingameDay()
    local events = util.sortedValues(state.events, function(event)
        return event.status == "active" and tonumber(event.event_day) >= today
    end, function(a, b)
        if a.event_day ~= b.event_day then return a.event_day < b.event_day end
        return (util.parseEventTime(a.event_time) or 0)
            < (util.parseEventTime(b.event_time) or 0)
    end)
    local output = {}
    for _, event in ipairs(events) do
        local sold, total, minimum = 0, 0, nil
        for _, typeId in ipairs(event.ticket_type_ids or {}) do
            local ticketType = state.ticket_types[typeId]
            if ticketType then
                sold = sold + ticketType.sold_quantity
                total = total + ticketType.total_quantity
                minimum = not minimum and ticketType.price or math.min(minimum, ticketType.price)
            end
        end
        output[#output + 1] = {
            event_id = event.event_id,
            title = event.title,
            description = event.description,
            location = event.location,
            event_day = event.event_day,
            event_time = event.event_time,
            sold = sold,
            total = total,
            from_price = minimum,
        }
    end
    return { events = output }
end

function actions.EVENT_DETAILS(payload)
    requireSession(payload)
    local event = state.events[payload.event_id]
    need(event and event.status == "active", "NOT_FOUND", "Event not found")
    local types = {}
    for _, id in ipairs(event.ticket_type_ids or {}) do
        local ticketType = state.ticket_types[id]
        if ticketType then
            local item = util.copy(ticketType)
            item.available_quantity = ticketType.total_quantity - ticketType.sold_quantity
            types[#types + 1] = item
        end
    end
    return { event = util.copy(event), ticket_types = types }
end

function actions.BUY_TICKETS(payload)
    local account = requireSession(payload)
    local event = state.events[payload.event_id]
    local ticketType = state.ticket_types[payload.ticket_type_id]
    need(event and event.status == "active" and ticketType
        and ticketType.event_id == event.event_id,
        "NOT_FOUND", "Ticket type not found")
    local quantity = math.floor(tonumber(payload.quantity) or 0)
    need(quantity >= 1 and quantity <= config.max_ticket_quantity,
        "BAD_QUANTITY", "Choose 1-" .. config.max_ticket_quantity .. " tickets")
    need(ticketType.sold_quantity + quantity <= ticketType.total_quantity,
        "SOLD_OUT", "Not enough tickets are left")
    need(verifyAccount(account, payload.pin), "BAD_PIN", "Incorrect PIN")
    local total = util.roundMoney(ticketType.price * quantity)
    need(account.balance >= total, "INSUFFICIENT_FUNDS", "Not enough money")

    local organizer = state.accounts[event.organizer_account_id]
    checkAccountActive(organizer)
    account.balance = util.roundMoney(account.balance - total)
    organizer.balance = util.roundMoney(organizer.balance + total)
    account.daily_spent = util.roundMoney(account.daily_spent + total)
    ticketType.sold_quantity = ticketType.sold_quantity + quantity
    if ticketType.sold_quantity >= ticketType.total_quantity then
        ticketType.status = "sold_out"
    end

    local tickets = {}
    for _ = 1, quantity do
        local ticket = {
            ticket_id = nextId("ticket"),
            event_id = event.event_id,
            ticket_type_id = ticketType.ticket_type_id,
            account_id = account.account_id,
            qr_code = util.randomString(8),
            used = false,
            status = "valid",
            purchased_day = util.ingameDay(),
        }
        state.tickets[ticket.ticket_id] = ticket
        tickets[#tickets + 1] = util.copy(ticket)
    end
    transaction(account, "ticket_purchase", -total, event.title,
        quantity .. "x " .. ticketType.name)
    transaction(organizer, "ticket_revenue", total, account.name,
        event.title .. " - " .. ticketType.name)
    notification(account, "Tickets purchased",
        quantity .. "x " .. ticketType.name .. " for " .. event.title, "event")
    notification(organizer, "Ticket sale",
        account.name .. " bought " .. quantity .. "x " .. ticketType.name, "money")
    save()
    logActivity("Tickets sold: " .. event.title .. " x" .. quantity, colors.magenta)
    return {
        tickets = tickets,
        total = total,
        balance = account.balance,
        event = util.copy(event),
        ticket_type = util.copy(ticketType),
    }
end

function actions.MY_TICKETS(payload)
    local account = requireSession(payload)
    local output = {}
    for _, ticket in pairs(state.tickets) do
        if ticket.account_id == account.account_id then
            local event = state.events[ticket.event_id]
            local ticketType = state.ticket_types[ticket.ticket_type_id]
            if event and ticketType then
                local item = util.copy(ticket)
                item.event_title = event.title
                item.location = event.location
                item.event_day = event.event_day
                item.event_time = event.event_time
                item.ticket_type_name = ticketType.name
                output[#output + 1] = item
            end
        end
    end
    table.sort(output, function(a, b)
        if a.event_day ~= b.event_day then return a.event_day < b.event_day end
        return a.event_time < b.event_time
    end)
    return { tickets = output }
end

function actions.DECLARATION_STATUS(payload)
    local account = requireSession(payload)
    local openPeriod
    for _, period in pairs(state.declaration_periods) do
        if period.status == "open" then openPeriod = period break end
    end
    if not openPeriod then return { period = nil } end
    local declaration = state.declarations[openPeriod.period_id]
        and state.declarations[openPeriod.period_id][account.account_id] or nil
    return {
        period = util.copy(openPeriod),
        declaration = util.copy(declaration),
        smart_lifetime = account.smart_declaration_lifetime,
    }
end

local function calculatePersonalDue(account, period)
    local income = 0
    for _, tx in ipairs(state.transactions) do
        if tx.account_id == account.account_id
            and tx.day >= period.start_day and tx.day <= period.end_day
            and tx.amount > 0
            and (tx.type == "transfer_in" or tx.type == "merchant_credit"
                or tx.type == "ticket_revenue") then
            income = income + tx.amount
        end
    end
    return util.roundMoney(income * period.personal_rate / 100), income
end

local function submitDeclaration(account, period, amount, smart)
    local declarations = state.declarations[period.period_id]
    declarations[account.account_id] = declarations[account.account_id] or {
        account_id = account.account_id,
        status = "requested",
    }
    local record = declarations[account.account_id]
    local due, income = calculatePersonalDue(account, period)
    local payment = amount
    local fee = 0
    if smart then
        payment = due
        if not account.smart_declaration_lifetime then
            fee = config.smart_declare_fee
        end
    end
    need(account.balance >= payment + fee, "INSUFFICIENT_FUNDS",
        "Not enough money for declaration and fee")
    account.balance = util.roundMoney(account.balance - payment - fee)
    state.tax_revenue = util.roundMoney(state.tax_revenue + payment + fee)
    record.status = "submitted"
    record.declared_amount = payment
    record.calculated_due = due
    record.taxable_income = income
    record.smart = smart == true
    record.fee = fee
    record.submitted_day = util.ingameDay()
    record.difference = util.roundMoney(due - payment)
    transaction(account, "tax_payment", -(payment + fee), "Government",
        smart and "Smart declaration" or "Tax declaration", { tax_amount = payment })
    if record.difference > 0 then
        notification(account, "Tax difference due",
            "Please pay " .. util.money(record.difference, config.currency)
                .. " more for period " .. period.period_id, "warning")
    elseif record.difference < 0 then
        local refund = math.abs(record.difference)
        account.balance = util.roundMoney(account.balance + refund)
        state.tax_revenue = util.roundMoney(state.tax_revenue - refund)
        transaction(account, "tax_refund", refund, "Government",
            "Tax overpayment refund", { tax_amount = -refund })
        record.refund = refund
    end
    save()
    return {
        declaration = util.copy(record),
        balance = account.balance,
    }
end

function actions.FILE_DECLARATION(payload)
    local account = requireSession(payload)
    local period = state.declaration_periods[payload.period_id]
    need(period and period.status == "open", "NO_PERIOD", "Tax period is closed")
    need(verifyAccount(account, payload.pin), "BAD_PIN", "Incorrect PIN")
    return submitDeclaration(account, period, validateAmount(payload.amount), false)
end

function actions.SMART_DECLARE(payload)
    local account = requireSession(payload)
    local period = state.declaration_periods[payload.period_id]
    need(period and period.status == "open", "NO_PERIOD", "Tax period is closed")
    need(verifyAccount(account, payload.pin), "BAD_PIN", "Incorrect PIN")
    if payload.buy_lifetime and not account.smart_declaration_lifetime then
        need(account.balance >= config.lifetime_smart_declare_fee,
            "INSUFFICIENT_FUNDS", "Not enough money for lifetime Smart Declare")
        account.balance = util.roundMoney(account.balance
            - config.lifetime_smart_declare_fee)
        state.tax_revenue = util.roundMoney(state.tax_revenue
            + config.lifetime_smart_declare_fee)
        account.smart_declaration_lifetime = true
        transaction(account, "service_fee", -config.lifetime_smart_declare_fee,
            "Government", "Lifetime Smart Declare")
    end
    return submitDeclaration(account, period, 0, true)
end

function actions.PAY_TAX_DIFFERENCE(payload)
    local account = requireSession(payload)
    local period = state.declaration_periods[payload.period_id]
    need(period, "NO_PERIOD", "Tax period not found")
    local record = state.declarations[period.period_id]
        and state.declarations[period.period_id][account.account_id]
    need(record and record.status == "submitted" and (record.difference or 0) > 0,
        "NOTHING_DUE", "No tax difference is due")
    need(verifyAccount(account, payload.pin), "BAD_PIN", "Incorrect PIN")
    local amount = util.roundMoney(record.difference)
    need(account.balance >= amount, "INSUFFICIENT_FUNDS",
        "Not enough money for the tax difference")
    account.balance = util.roundMoney(account.balance - amount)
    state.tax_revenue = util.roundMoney(state.tax_revenue + amount)
    record.supplemental_payment = util.roundMoney(
        (record.supplemental_payment or 0) + amount)
    record.declared_amount = util.roundMoney((record.declared_amount or 0) + amount)
    record.difference = 0
    record.settled_day = util.ingameDay()
    transaction(account, "tax_payment", -amount, "Government",
        "Tax difference for " .. period.period_id, { tax_amount = amount })
    notification(account, "Tax settled",
        period.period_id .. " is now fully paid", "success")
    save()
    return {
        declaration = util.copy(record),
        paid = amount,
        balance = account.balance,
    }
end

-- Service kiosk routes -------------------------------------------------------

function actions.KIOSK_REGISTER(payload)
    if payload.terminal_id and payload.terminal_token then
        local existing = state.terminals[payload.terminal_id]
        if existing and existing.auth_token == payload.terminal_token then
            existing.last_seen = util.nowMs()
            return {
                terminal_id = existing.terminal_id,
                terminal_token = existing.auth_token,
                name = existing.name,
                linked = existing.company_id ~= nil,
            }
        end
    end
    local terminalId = nextId("terminal")
    local terminal = {
        terminal_id = terminalId,
        auth_token = util.token("TERMINAL"),
        name = util.safeText(payload.name or ("Kiosk " .. terminalId), 24),
        company_id = nil,
        quick_items = {},
        balance = 0,
        sales_total = 0,
        status = "active",
        created_day = util.ingameDay(),
        last_seen = util.nowMs(),
    }
    state.terminals[terminalId] = terminal
    save()
    logActivity("Registered " .. terminal.name, colors.orange)
    return {
        terminal_id = terminalId,
        terminal_token = terminal.auth_token,
        name = terminal.name,
        linked = false,
    }
end

function actions.KIOSK_OWNER_LOGIN(payload)
    requireTerminal(payload)
    local account = accountByName(payload.name)
    need(verifyAccount(account, payload.pin), "BAD_LOGIN", "Owner name or PIN is wrong")
    checkAccountActive(account)
    return {
        owner_session = createSession(account),
        owner = publicAccount(account),
    }
end

function actions.OWNER_COMPANIES(payload)
    local owner = requireSession({ session_token = payload.owner_session })
    local output = util.sortedValues(state.companies, function(company)
        return company.owner_account_id == owner.account_id
            and company.status == "active"
    end, function(a, b) return a.name < b.name end)
    return { companies = util.copy(output) }
end

function actions.CREATE_COMPANY(payload)
    local owner = requireSession({ session_token = payload.owner_session })
    local name = util.safeText(util.trim(payload.company_name), 28)
    need(#name >= 2, "INVALID_NAME", "Company name is too short")
    for _, company in pairs(state.companies) do
        need(util.normalName(company.name) ~= util.normalName(name),
            "NAME_TAKEN", "Company name is taken")
    end
    local companyId = nextId("company")
    local company = {
        company_id = companyId,
        name = name,
        tax_id = "TX-" .. util.randomString(6),
        owner_account_id = owner.account_id,
        linked_terminal_ids = {},
        quick_items = {},
        status = "active",
        created_day = util.ingameDay(),
    }
    state.companies[companyId] = company
    save()
    return { company = util.copy(company) }
end

function actions.LINK_TERMINAL(payload)
    local terminal = requireTerminal(payload)
    local owner = requireSession({ session_token = payload.owner_session })
    local company = state.companies[payload.company_id]
    need(company and company.owner_account_id == owner.account_id,
        "NOT_OWNER", "You do not own that company")
    terminal.company_id = company.company_id
    local found = false
    for _, id in ipairs(company.linked_terminal_ids) do
        if id == terminal.terminal_id then found = true break end
    end
    if not found then company.linked_terminal_ids[#company.linked_terminal_ids + 1]
        = terminal.terminal_id end
    save()
    logActivity(terminal.name .. " linked to " .. company.name, colors.cyan)
    return { company = util.copy(company), terminal = util.copy(terminal) }
end

function actions.KIOSK_STATE(payload)
    local terminal = requireTerminal(payload)
    cleanupEphemeral()
    local company, owner = companyOwner(terminal)
    return {
        terminal = {
            terminal_id = terminal.terminal_id,
            name = terminal.name,
            company_id = terminal.company_id,
            balance = merchantBalance(terminal),
            sales_total = terminal.sales_total,
        },
        company = company and {
            company_id = company.company_id,
            name = company.name,
            tax_id = company.tax_id,
            owner_name = owner and owner.name,
        } or nil,
        quick_items = util.copy(quickItems(terminal)),
    }
end

function actions.ADD_QUICK_ITEM(payload)
    local terminal = requireTerminal(payload)
    local items = quickItems(terminal)
    need(#items < 40, "ITEM_LIMIT", "Maximum 40 quick items")
    local name = util.safeText(util.trim(payload.name), 20)
    need(#name >= 1, "INVALID_NAME", "Item needs a name")
    local price = validateAmount(payload.price, 1000000)
    local item = {
        item_id = util.token("ITEM"):sub(1, 13),
        name = name,
        price = price,
    }
    items[#items + 1] = item
    save()
    return { item = util.copy(item), quick_items = util.copy(items) }
end

function actions.REMOVE_QUICK_ITEM(payload)
    local terminal = requireTerminal(payload)
    local items = quickItems(terminal)
    for index, item in ipairs(items) do
        if item.item_id == payload.item_id then
            table.remove(items, index)
            save()
            return { quick_items = util.copy(items) }
        end
    end
    reject("NOT_FOUND", "Item not found")
end

local function uniqueCode(length)
    local code
    repeat code = util.randomString(length) until not state.active_pay_codes[code]
    return code
end

function actions.CREATE_PAY_CODE(payload)
    local terminal = requireTerminal(payload)
    local amount = validateAmount(payload.amount, 1000000)
    local code = uniqueCode(6)
    local items = {}
    for index, item in ipairs(payload.items or {}) do
        if index > 30 then break end
        items[#items + 1] = {
            name = util.safeText(item.name, 20),
            price = validateAmount(item.price, 1000000),
            quantity = math.max(1, math.floor(tonumber(item.quantity) or 1)),
        }
    end
    state.active_pay_codes[code] = {
        code = code,
        kind = "sale",
        amount = amount,
        items = items,
        description = util.safeText(payload.description or "Purchase", 80),
        terminal_id = terminal.terminal_id,
        company_id = terminal.company_id,
        status = "pending",
        created_at = util.nowMs(),
        expires_at = util.nowMs() + config.payment_code_ttl_ms,
    }
    save()
    return {
        code = code,
        amount = amount,
        expires_at = state.active_pay_codes[code].expires_at,
    }
end

function actions.CREATE_WITHDRAWAL_CODE(payload)
    local terminal = requireTerminal(payload)
    local amount = validateAmount(payload.amount, merchantBalance(terminal))
    local code = uniqueCode(6)
    state.active_pay_codes[code] = {
        code = code,
        kind = "withdrawal",
        amount = amount,
        description = util.safeText(payload.description or "Kiosk withdrawal", 80),
        terminal_id = terminal.terminal_id,
        company_id = terminal.company_id,
        status = "pending",
        created_at = util.nowMs(),
        expires_at = util.nowMs() + config.payment_code_ttl_ms,
    }
    save()
    return {
        code = code,
        amount = amount,
        expires_at = state.active_pay_codes[code].expires_at,
    }
end

function actions.CODE_STATUS(payload)
    local terminal = requireTerminal(payload)
    cleanupEphemeral()
    local payment = state.active_pay_codes[string.upper(payload.code or "")]
    need(payment and payment.terminal_id == terminal.terminal_id,
        "NOT_FOUND", "Code not found")
    local payer = payment.paid_by and state.accounts[payment.paid_by]
    return {
        status = payment.status,
        amount = payment.amount,
        payer = payer and payer.name,
        expires_in_ms = math.max(0, payment.expires_at - util.nowMs()),
    }
end

function actions.CANCEL_CODE(payload)
    local terminal = requireTerminal(payload)
    local code = string.upper(util.trim(payload.code))
    local payment = state.active_pay_codes[code]
    need(payment and payment.terminal_id == terminal.terminal_id,
        "NOT_FOUND", "Code not found")
    need(payment.status == "pending", "ALREADY_COMPLETE",
        "Code has already been completed")
    payment.status = "cancelled"
    payment.cancelled_at = util.nowMs()
    save()
    return { status = "cancelled" }
end

function actions.CREATE_SUBSCRIPTION(payload)
    local terminal = requireTerminal(payload)
    local customer = accountByName(payload.customer_name)
    checkAccountActive(customer)
    need(verifyAccount(customer, payload.customer_pin), "BAD_PIN", "Customer PIN is wrong")
    local amount = validateAmount(payload.amount, 1000000)
    local id = nextId("subscription")
    customer.subscriptions[id] = {
        subscription_id = id,
        amount = amount,
        description = util.safeText(payload.description, 60),
        kiosk_id = terminal.terminal_id,
        company_id = terminal.company_id,
        next_charge_day = util.ingameDay() + 1,
        active = true,
        created_day = util.ingameDay(),
    }
    notification(customer, "Subscription started",
        util.safeText(payload.description, 40) .. " - "
            .. util.money(amount, config.currency) .. "/day", "subscription")
    save()
    return { subscription = util.copy(customer.subscriptions[id]) }
end

function actions.PROXIMITY_FIND(payload)
    requireTerminal(payload)
    need(type(payload.x) == "number" and type(payload.y) == "number"
        and type(payload.z) == "number", "GPS_FAILED", "Kiosk has no GPS fix")
    local best, bestDistance
    for accountId, position in pairs(state.gps_devices) do
        if position.updated_at + config.gps_ttl_ms > util.nowMs() then
            local distance = math.sqrt((position.x - payload.x) ^ 2
                + (position.y - payload.y) ^ 2
                + (position.z - payload.z) ^ 2)
            if distance <= (payload.radius or 32)
                and (not bestDistance or distance < bestDistance) then
                best = state.accounts[accountId]
                bestDistance = distance
            end
        end
    end
    need(best, "NO_NEARBY_DEVICE", "No nearby PUMPE found")
    return { customer = best.name, distance = bestDistance }
end

function actions.PROXIMITY_REQUEST(payload)
    local terminal = requireTerminal(payload)
    local customer = accountByName(payload.customer_name)
    checkAccountActive(customer)
    local amount = validateAmount(payload.amount, 1000000)
    local id = nextId("request")
    state.payment_requests[id] = {
        request_id = id,
        terminal_id = terminal.terminal_id,
        account_id = customer.account_id,
        amount = amount,
        description = util.safeText(payload.description or "Proximity payment", 80),
        status = "pending",
        created_at = util.nowMs(),
        expires_at = util.nowMs() + 90 * 1000,
    }
    notification(customer, "Payment request",
        terminal.name .. " requests " .. util.money(amount, config.currency),
        "request")
    save()
    return { request_id = id, status = "pending" }
end

function actions.REQUEST_STATUS(payload)
    local terminal = requireTerminal(payload)
    local request = state.payment_requests[payload.request_id]
    need(request and request.terminal_id == terminal.terminal_id,
        "NOT_FOUND", "Request not found")
    return { status = request.status }
end

-- Event organizer routes ----------------------------------------------------

function actions.EVENT_DASHBOARD(payload)
    local owner = requireSession(payload)
    local active, sold, revenue = 0, 0, 0
    for _, event in pairs(state.events) do
        if event.organizer_account_id == owner.account_id then
            if event.status == "active" then active = active + 1 end
            for _, typeId in ipairs(event.ticket_type_ids or {}) do
                local ticketType = state.ticket_types[typeId]
                if ticketType then
                    sold = sold + ticketType.sold_quantity
                    revenue = revenue + ticketType.sold_quantity * ticketType.price
                end
            end
        end
    end
    return {
        account = publicAccount(owner),
        active_events = active,
        tickets_sold = sold,
        revenue = util.roundMoney(revenue),
    }
end

function actions.CREATE_EVENT(payload)
    local owner = requireSession(payload)
    local title = util.safeText(util.trim(payload.title), 40)
    need(#title >= 2, "INVALID_TITLE", "Event title is too short")
    local day = math.floor(tonumber(payload.event_day) or -1)
    need(day >= util.ingameDay(), "INVALID_DAY", "Event day is in the past")
    need(util.parseEventTime(payload.event_time), "INVALID_TIME", "Use time HH:MM")
    local id = nextId("event")
    local event = {
        event_id = id,
        title = title,
        description = util.safeText(payload.description, 120),
        location = util.safeText(payload.location, 60),
        event_day = day,
        event_time = payload.event_time,
        organizer_account_id = owner.account_id,
        ticket_type_ids = {},
        status = "active",
        created_day = util.ingameDay(),
    }
    state.events[id] = event
    save()
    logActivity("Event created: " .. title, colors.magenta)
    return { event = util.copy(event) }
end

function actions.MY_EVENTS(payload)
    local owner = requireSession(payload)
    local output = util.sortedValues(state.events, function(event)
        return event.organizer_account_id == owner.account_id
    end, function(a, b) return a.event_day < b.event_day end)
    for _, event in ipairs(output) do
        event.ticket_types = {}
        for _, id in ipairs(event.ticket_type_ids or {}) do
            event.ticket_types[#event.ticket_types + 1] = util.copy(state.ticket_types[id])
        end
    end
    return { events = util.copy(output) }
end

local function ownedEvent(payload)
    local owner = requireSession(payload)
    local event = state.events[payload.event_id]
    need(event and event.organizer_account_id == owner.account_id,
        "NOT_OWNER", "Event not found or not yours")
    return owner, event
end

function actions.ADD_TICKET_TYPE(payload)
    local _, event = ownedEvent(payload)
    local name = util.safeText(util.trim(payload.name), 28)
    need(#name >= 1, "INVALID_NAME", "Ticket type needs a name")
    local price = validateAmount(payload.price, 1000000)
    local quantity = math.floor(tonumber(payload.quantity) or 0)
    need(quantity >= 1 and quantity <= 100000,
        "INVALID_QUANTITY", "Quantity must be 1-100000")
    local id = nextId("ticket_type")
    local ticketType = {
        ticket_type_id = id,
        event_id = event.event_id,
        name = name,
        description = util.safeText(payload.description, 80),
        price = price,
        total_quantity = quantity,
        sold_quantity = 0,
        perks = payload.perks or {},
        status = "available",
    }
    state.ticket_types[id] = ticketType
    event.ticket_type_ids[#event.ticket_type_ids + 1] = id
    save()
    return { ticket_type = util.copy(ticketType) }
end

function actions.VERIFY_TICKET(payload)
    local owner = requireSession(payload)
    local code = string.upper(util.trim(payload.code))
    local found
    for _, ticket in pairs(state.tickets) do
        if ticket.qr_code == code then found = ticket break end
    end
    need(found, "NOT_FOUND", "Ticket code not found")
    local event = state.events[found.event_id]
    need(event and event.organizer_account_id == owner.account_id,
        "NOT_OWNER", "Ticket is for another organizer")
    local ticketType = state.ticket_types[found.ticket_type_id]
    local holder = state.accounts[found.account_id]
    return {
        ticket = util.copy(found),
        event = util.copy(event),
        ticket_type = util.copy(ticketType),
        holder = holder and holder.name or "Unknown",
        valid = found.status == "valid" and not found.used
            and event.status == "active",
    }
end

function actions.MARK_TICKET_USED(payload)
    local owner = requireSession(payload)
    local ticket = state.tickets[payload.ticket_id]
    need(ticket, "NOT_FOUND", "Ticket not found")
    local event = state.events[ticket.event_id]
    need(event and event.organizer_account_id == owner.account_id,
        "NOT_OWNER", "Ticket is for another organizer")
    need(ticket.status == "valid" and not ticket.used,
        "ALREADY_USED", "Ticket has already been used")
    ticket.used = true
    ticket.status = "used"
    ticket.used_day = util.ingameDay()
    ticket.used_time = util.formatClock()
    save()
    logActivity("Ticket admitted: " .. ticket.qr_code, colors.lime)
    return { ticket = util.copy(ticket) }
end

-- Government routes --------------------------------------------------------

function actions.GOVERNMENT_LOGIN(payload)
    need(config.government_key ~= "CHANGE-ME-GOVERNMENT-KEY",
        "CONFIG_REQUIRED", "Change government_key in config.lua first")
    need(payload.key == config.government_key,
        "BAD_KEY", "Government key is incorrect")
    local token = util.token("GOV")
    governmentSessions[token] = {
        expires_at = util.nowMs() + config.session_ttl_ms,
    }
    logActivity("Government controller login", colors.orange)
    return { government_token = token }
end

function actions.GOVERNMENT_STATS(payload)
    requireGovernment(payload)
    local companies, declarations = 0, 0
    for _ in pairs(state.companies) do companies = companies + 1 end
    for _, period in pairs(state.declarations) do
        for _ in pairs(period) do declarations = declarations + 1 end
    end
    local accounts = 0
    for _ in pairs(state.accounts) do accounts = accounts + 1 end
    return {
        accounts = accounts,
        companies = companies,
        transactions = #state.transactions,
        declarations = declarations,
        tax_revenue = state.tax_revenue,
        version = config.version,
        uptime = math.floor(os.clock()),
        day = util.ingameDay(),
    }
end

function actions.TAX_OVERVIEW(payload)
    requireGovernment(payload)
    local periods = util.sortedValues(state.declaration_periods, nil, function(a, b)
        return a.start_day > b.start_day
    end)
    local output = {}
    for _, period in ipairs(periods) do
        local requested, submitted, collected = 0, 0, 0
        for _, declaration in pairs(state.declarations[period.period_id] or {}) do
            requested = requested + 1
            if declaration.status == "submitted" then
                submitted = submitted + 1
                collected = collected + (declaration.declared_amount or 0)
                    + (declaration.fee or 0)
            end
        end
        local item = util.copy(period)
        item.requested = requested
        item.submitted = submitted
        item.collected = util.roundMoney(collected)
        output[#output + 1] = item
    end
    return {
        periods = output,
        total_revenue = state.tax_revenue,
    }
end

function actions.OPEN_TAX_PERIOD(payload)
    requireGovernment(payload)
    for _, existing in pairs(state.declaration_periods) do
        need(existing.status ~= "open", "PERIOD_OPEN", "A period is already open")
    end
    local endDay = math.floor(tonumber(payload.end_day) or 0)
    need(endDay >= util.ingameDay(), "INVALID_DAY", "End day cannot be in the past")
    local personalRate = tonumber(payload.personal_rate)
    local commercialRate = tonumber(payload.commercial_rate)
    local threshold = tonumber(payload.threshold)
    need(personalRate and personalRate >= 0 and personalRate <= 100,
        "INVALID_RATE", "Personal rate must be 0-100")
    need(commercialRate and commercialRate >= 0 and commercialRate <= 100,
        "INVALID_RATE", "Commercial rate must be 0-100")
    need(threshold and threshold >= 0, "INVALID_THRESHOLD", "Threshold is invalid")
    local id = nextId("period")
    local period = {
        period_id = id,
        start_day = util.ingameDay(),
        end_day = endDay,
        personal_rate = personalRate,
        commercial_rate = commercialRate,
        threshold = threshold,
        status = "open",
    }
    state.declaration_periods[id] = period
    state.declarations[id] = {}
    for accountId, account in pairs(state.accounts) do
        local _, income = calculatePersonalDue(account, period)
        if income >= threshold then
            state.declarations[id][accountId] = {
                account_id = accountId,
                status = "requested",
            }
            notification(account, "Tax declaration open",
                "File by in-game day " .. endDay, "tax")
        end
    end
    save()
    logActivity("Tax period opened: " .. id, colors.orange)
    return { period = util.copy(period) }
end

function actions.SET_TAX_RATES(payload)
    requireGovernment(payload)
    local period
    for _, candidate in pairs(state.declaration_periods) do
        if candidate.status == "open" then period = candidate break end
    end
    need(period, "NO_PERIOD", "No tax period is open")
    local personalRate = tonumber(payload.personal_rate)
    local commercialRate = tonumber(payload.commercial_rate)
    need(personalRate and personalRate >= 0 and personalRate <= 100,
        "INVALID_RATE", "Personal rate must be 0-100")
    need(commercialRate and commercialRate >= 0 and commercialRate <= 100,
        "INVALID_RATE", "Commercial rate must be 0-100")
    period.personal_rate = personalRate
    period.commercial_rate = commercialRate
    save()
    return { period = util.copy(period) }
end

function actions.CLOSE_TAX_PERIOD(payload)
    requireGovernment(payload)
    local period = state.declaration_periods[payload.period_id]
    need(period and period.status == "open", "NO_PERIOD", "Period is not open")
    period.status = "closed"
    period.closed_day = util.ingameDay()
    save()
    logActivity("Tax period closed: " .. period.period_id, colors.red)
    return { period = util.copy(period) }
end

function actions.STATE_DEPOSIT(payload)
    requireGovernment(payload)
    local account = accountByName(payload.recipient)
    checkAccountActive(account)
    local amount = validateAmount(payload.amount, 1000000000)
    account.balance = util.roundMoney(account.balance + amount)
    transaction(account, "state_deposit", amount, "Government",
        payload.reason or "State deposit")
    notification(account, "State deposit",
        util.money(amount, config.currency) .. " - "
            .. util.safeText(payload.reason or "Government payment", 60), "money")
    save()
    logActivity("State deposit to " .. account.name, colors.lime)
    return { account = publicAccount(account), amount = amount }
end

function actions.AUDIT_COMPANY(payload)
    requireGovernment(payload)
    local query = util.normalName(payload.query)
    local found
    for _, company in pairs(state.companies) do
        if util.normalName(company.name) == query
            or util.normalName(company.tax_id) == query then
            found = company break
        end
    end
    need(found, "NOT_FOUND", "Company not found")
    local owner = state.accounts[found.owner_account_id]
    return {
        company = util.copy(found),
        owner_name = owner and owner.name,
    }
end

local function processSubscriptions()
    local today = util.ingameDay()
    if state.last_subscription_day == today then return end
    state.last_subscription_day = today
    local changed = false
    for _, account in pairs(state.accounts) do
        for _, subscription in pairs(account.subscriptions or {}) do
            if subscription.active and subscription.next_charge_day <= today then
                local terminal = state.terminals[subscription.kiosk_id]
                if terminal and account.balance >= subscription.amount
                    and not account.frozen and not account.banned then
                    account.balance = util.roundMoney(account.balance - subscription.amount)
                    creditMerchant(terminal, subscription.amount,
                        subscription.description, account)
                    transaction(account, "subscription", -subscription.amount,
                        terminal.name, subscription.description, {
                            company_id = subscription.company_id,
                            terminal_id = terminal.terminal_id,
                        })
                    notification(account, "Subscription charged",
                        subscription.description .. " -"
                            .. util.money(subscription.amount, config.currency),
                        "subscription")
                else
                    notification(account, "Subscription failed",
                        subscription.description .. " - insufficient funds",
                        "warning")
                end
                subscription.next_charge_day = today + 1
                changed = true
            end
        end
    end
    if changed then
        save()
        logActivity("Daily subscriptions processed", colors.cyan)
    end
end

local function deploymentChecksum(body)
    return util.checksum(body)
end

local function deploymentReply(recipient, requestId, ok, data, err, code)
    rednet.send(recipient, {
        version = 1,
        kind = "deploy_response",
        request_id = requestId,
        ok = ok == true,
        data = data,
        error = err,
        code = code,
    }, DEPLOY_PROTOCOL)
end

local function deploymentError(recipient, requestId, code, message)
    deploymentReply(recipient, requestId, false, nil, message, code)
end

local function authorizedDeploymentRole(role, code)
    if not ROLE_MAIN_FILES[role] then
        return false, "INVALID_ROLE", "Unknown PUMPE role"
    end
    if protectedDeployRole(role) and tostring(code or "") ~= DEPLOY_CODE then
        return false, "PROTECTED_ROLE", "Download code is incorrect"
    end
    return true
end

local function deploymentSourceFor(role, requestedPath)
    for _, file in ipairs(deploymentFilesForRole(role) or {}) do
        if file.path == requestedPath then return file.source end
    end
    return nil
end

local function deploymentManifest(role)
    local files = deploymentFilesForRole(role)
    if not files then return nil, "Unknown PUMPE role" end
    local manifest = {}
    for _, file in ipairs(files) do
        local sourcePath = fs.combine(UPDATES_DIR, file.source)
        if not fs.exists(sourcePath) or fs.isDir(sourcePath) then
            return nil, "Update depot is missing " .. file.source
        end
        local body = util.readFile(sourcePath)
        if not body then return nil, "Could not read " .. file.source end
        manifest[#manifest + 1] = {
            path = file.path,
            size = #body,
            checksum = deploymentChecksum(body),
        }
    end
    return manifest
end

local function deploymentRoute(sender, message)
    if type(message) ~= "table" or message.kind ~= "deploy_request"
        or type(message.request_id) ~= "string" then return end
    local payload = type(message.payload) == "table" and message.payload or {}
    local role = string.lower(tostring(payload.role or ""))
    local authorized, authCode, authMessage =
        authorizedDeploymentRole(role, payload.code)
    if not authorized then
        deploymentError(sender, message.request_id, authCode, authMessage)
        return
    end

    if message.action == "MANIFEST" then
        local manifest, err = deploymentManifest(role)
        if not manifest then
            deploymentError(sender, message.request_id, "DEPOT_INCOMPLETE", err)
            return
        end
        deploymentReply(sender, message.request_id, true, {
            role = role,
            version = config.version,
            install_root = "/pumpe",
            chunk_size = DEPLOY_CHUNK_SIZE,
            files = manifest,
        })
    elseif message.action == "FILE_CHUNK" then
        local requestedPath = tostring(payload.path or "")
        local source = deploymentSourceFor(role, requestedPath)
        if not source then
            deploymentError(sender, message.request_id, "FILE_DENIED",
                "File is not part of this role")
            return
        end
        local sourcePath = fs.combine(UPDATES_DIR, source)
        local body = util.readFile(sourcePath)
        if not body then
            deploymentError(sender, message.request_id, "FILE_MISSING",
                "Update file is unavailable")
            return
        end
        local offset = math.floor(tonumber(payload.offset) or -1)
        local limit = math.floor(tonumber(payload.limit) or DEPLOY_CHUNK_SIZE)
        if offset < 0 or offset > #body then
            deploymentError(sender, message.request_id, "BAD_OFFSET",
                "Invalid file offset")
            return
        end
        limit = math.max(1, math.min(DEPLOY_CHUNK_SIZE, limit))
        local chunk = body:sub(offset + 1, offset + limit)
        local nextOffset = offset + #chunk
        deploymentReply(sender, message.request_id, true, {
            path = requestedPath,
            offset = offset,
            data = chunk,
            next_offset = nextOffset,
            done = nextOffset >= #body,
            total_size = #body,
        })
    else
        deploymentError(sender, message.request_id, "UNKNOWN_ACTION",
            "Unknown deployment action")
    end
end

local function route(sender, message)
    if type(message) ~= "table" or message.kind ~= "request"
        or type(message.action) ~= "string" then return end
    local handler = actions[message.action]
    if not handler then
        net.reply(sender, config.protocol, message.request_id, false, nil,
            "Unknown bank action", "UNKNOWN_ACTION")
        return
    end
    local ok, result = pcall(handler, message.payload or {}, sender)
    if ok then
        net.reply(sender, config.protocol, message.request_id, true, result)
    elseif type(result) == "table" and result.pumpe then
        net.reply(sender, config.protocol, message.request_id, false, nil,
            result.message, result.code)
    else
        logActivity("Server error: " .. tostring(result), colors.red)
        net.reply(sender, config.protocol, message.request_id, false, nil,
            "Internal bank error", "SERVER_ERROR")
    end
end

local ONLINE_UPDATE_STAGE = fs.combine(ROOT, ".online_update_stage")
local ONLINE_UPDATE_BACKUP = fs.combine(ROOT, ".online_update_backup")
local onlineUpdateStatus = tostring(config.update_manifest_url or "") ~= ""
    and "CHECKING" or "URL NOT CONFIGURED"
local onlineUpdateColor = tostring(config.update_manifest_url or "") ~= ""
    and colors.orange or colors.lightGray
local lastOnlineUpdateError

local function loadConfigTable(path)
    local loader, loadError = loadfile(path)
    if not loader then return nil, loadError end
    local ok, value = pcall(loader)
    if not ok or type(value) ~= "table" then
        return nil, ok and "Config did not return a table" or tostring(value)
    end
    return value
end

local function preserveLocalConfig(manifest)
    local stagedPath = fs.combine(ONLINE_UPDATE_STAGE, "config.lua")
    local defaults, err = loadConfigTable(stagedPath)
    if not defaults then return nil, "Downloaded config is invalid: " .. tostring(err) end
    if tostring(defaults.version or "") ~= manifest.version then
        return nil, "Downloaded config version does not match the manifest"
    end

    local merged = util.copy(defaults)
    for key, value in pairs(config) do
        if key ~= "version" then merged[key] = util.copy(value) end
    end
    merged.version = manifest.version
    util.writeFile(stagedPath,
        "-- PUMPE configuration. Local settings are preserved during updates.\n"
        .. "return " .. textutils.serialize(merged, { compact = false }) .. "\n")
    return true
end

local function checkForOnlineUpdate()
    if config.auto_update == false then
        onlineUpdateStatus = "DISABLED"
        onlineUpdateColor = colors.lightGray
        return false
    end
    local manifestUrl = tostring(config.update_manifest_url or "")
    if manifestUrl == "" then
        onlineUpdateStatus = "URL NOT CONFIGURED"
        onlineUpdateColor = colors.lightGray
        return false
    end

    onlineUpdateStatus = "CHECKING INTERNET"
    onlineUpdateColor = colors.orange
    local manifest, err = onlineUpdate.fetchManifest(
        manifestUrl, LOCAL_UPDATE_FILES, config.update_channel or "stable")
    if not manifest then
        onlineUpdateStatus = "CHECK FAILED"
        onlineUpdateColor = colors.red
        if err ~= lastOnlineUpdateError then
            logActivity("Online update: " .. tostring(err), colors.red)
            lastOnlineUpdateError = err
        end
        return false
    end
    lastOnlineUpdateError = nil

    if not onlineUpdate.isNewer(manifest.version, config.version) then
        onlineUpdateStatus = "CURRENT v" .. config.version
        onlineUpdateColor = colors.lime
        return false
    end

    onlineUpdateStatus = "DOWNLOADING v" .. manifest.version
    onlineUpdateColor = colors.cyan
    logActivity("Online update found: v" .. manifest.version, colors.cyan)
    local downloaded, downloadError = onlineUpdate.downloadRelease(
        manifest, manifestUrl, ONLINE_UPDATE_STAGE,
        function(_, index, total)
            onlineUpdateStatus = "DOWNLOADING " .. index .. "/" .. total
        end)
    if not downloaded then
        onlineUpdateStatus = "DOWNLOAD FAILED"
        onlineUpdateColor = colors.red
        logActivity("Online update failed: " .. tostring(downloadError), colors.red)
        return false
    end

    local preserved, preserveError = preserveLocalConfig(manifest)
    if not preserved then
        if fs.exists(ONLINE_UPDATE_STAGE) then fs.delete(ONLINE_UPDATE_STAGE) end
        onlineUpdateStatus = "CONFIG REJECTED"
        onlineUpdateColor = colors.red
        logActivity("Online update failed: " .. tostring(preserveError), colors.red)
        return false
    end

    onlineUpdateStatus = "INSTALLING v" .. manifest.version
    onlineUpdateColor = colors.orange
    local committed, commitError = onlineUpdate.commitRelease(
        manifest, ONLINE_UPDATE_STAGE, ROOT, ONLINE_UPDATE_BACKUP)
    if not committed then
        onlineUpdateStatus = "ROLLED BACK"
        onlineUpdateColor = colors.red
        logActivity("Online update rolled back: " .. tostring(commitError), colors.red)
        return false
    end

    pcall(save)
    onlineUpdateStatus = "RESTARTING v" .. manifest.version
    onlineUpdateColor = colors.lime
    logActivity("Online update installed; restarting", colors.lime)
    sleep(0.8)
    os.reboot()
    return true
end

local function serverLoop()
    while running do
        local sender, message = rednet.receive(config.protocol, 1)
        if sender then route(sender, message) end
    end
end

local function deploymentLoop()
    while running do
        local sender, message = rednet.receive(DEPLOY_PROTOCOL, 1)
        if sender then
            local ok, err = pcall(deploymentRoute, sender, message)
            if not ok then
                logActivity("Deployment error: " .. tostring(err), colors.red)
                if type(message) == "table" and message.request_id then
                    deploymentError(sender, message.request_id, "DEPLOY_ERROR",
                        "Bank deployment service failed")
                end
            end
        end
    end
end

local function schedulerLoop()
    while running do
        cleanupEphemeral()
        processSubscriptions()
        sleep(10)
    end
end

local function onlineUpdateLoop()
    while running do
        checkForOnlineUpdate()
        local interval = math.max(5,
            math.floor(tonumber(config.update_check_seconds) or 10))
        sleep(interval)
    end
end

local function count(map)
    local value = 0
    for _ in pairs(map) do value = value + 1 end
    return value
end

local function dashboardLoop()
    local target = term.current()
    local blink = true
    while running do
        local width, height = target.getSize()
        ui.clear(target)
        ui.header(target, "PUMPE BANK SERVER", "v" .. config.version,
            util.formatClock(blink))
        ui.text(target, 2, 5, "LIVE NETWORK", colors.lime)
        ui.card(target, 2, 7, math.floor((width - 5) / 2), 4, colors.cyan)
        ui.text(target, 4, 8, "ACCOUNTS", colors.lightGray, colors.gray)
        ui.text(target, 4, 9, tostring(count(state.accounts)), colors.white, colors.gray)
        local rightX = math.floor((width - 5) / 2) + 4
        ui.card(target, rightX, 7, width - rightX, 4, colors.magenta)
        ui.text(target, rightX + 2, 8, "TRANSACTIONS", colors.lightGray, colors.gray)
        ui.text(target, rightX + 2, 9, tostring(#state.transactions), colors.white, colors.gray)
        ui.text(target, 2, 11,
            ui.truncate("ONLINE UPDATE  " .. onlineUpdateStatus, width - 2),
            onlineUpdateColor)

        local scene = ui.scene(target)
        local feedY = 12
        ui.text(target, 2, feedY, "ACTIVITY", colors.lightGray)
        local maxFeed = math.max(1, height - feedY - 3)
        for index = 1, math.min(#activity, maxFeed) do
            local item = activity[index]
            ui.text(target, 2, feedY + index,
                item.time .. "  " .. ui.truncate(item.text, width - 10), item.color)
        end
        scene:button("save", width - 18, height - 1, 8, 1, "SAVE",
            { background = colors.blue })
        scene:button("stop", width - 9, height - 1, 8, 1, "STOP",
            { background = colors.red })
        local action = scene:wait({ tickRate = 0.5, flash = false })
        blink = not blink
        if action == "save" then
            save()
            logActivity("Manual save complete", colors.lime)
        elseif action == "stop" then
            if ui.confirm(target, "STOP SERVER", "Save and shut down?", "STOP", "BACK") then
                running = false
                save()
                return
            end
        elseif action == "__terminate" then
            running = false
            save()
            return
        end
    end
end

ui.boot(term.current(), "PUMPE BANK", "SECURE ECONOMY CORE")
net.host(config.protocol, config.hostname)
rednet.host(DEPLOY_PROTOCOL, DEPLOY_HOSTNAME)
logActivity("Server online on computer #" .. os.getComputerID(), colors.lime)
local depotMissing = updateDepotMissingFiles()
if #depotMissing == 0 then
    logActivity("Easy Deployment online", colors.lime)
else
    logActivity("Deployment missing " .. #depotMissing .. " files", colors.orange)
end
save()

parallel.waitForAny(serverLoop, deploymentLoop, schedulerLoop,
    onlineUpdateLoop, dashboardLoop)
pcall(rednet.unhost, config.protocol)
pcall(rednet.unhost, DEPLOY_PROTOCOL)
ui.clear(term.current())
print("PUMPE Bank Server stopped safely.")
